# Generated by Django 5.2.8 on 2025-12-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoo',
            name='description',
            field=models.TextField(default='No Description', max_length=255),
        ),
    ]
